// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Kino_system_overwrite","status":true,"description":"修改部分系統功能","parameters":{}},
{"name":"Kino_menu","status":true,"description":"選單視窗的變更","parameters":{}}
];
